name: ğŸ” update

on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  update:
    name: update
    runs-on: macOS-latest
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: ğŸŒŠ Install gallery-workflow
        run: |
          rm -f .build/release/gallery-workflow
          curl -L https://github.com/$GITHUB_REPOSITORY-workflow/releases/latest/download/gallery-workflow.zip --output gallery-workflow.zip
          unzip gallery-workflow.zip
          rm gallery-workflow.zip
          if [ -f .build/release/gallery-workflow ]; then
            echo "gallery-workflow installed"
          else
            echo "gallery-workflow cannot be downloaded using url https://github.com/$GITHUB_REPOSITORY-workflow/releases/latest/download/gallery-workflow.zip"
            exit 1
          fi
      - name: ğŸ· Update releases
        run: |
          .build/release/gallery-workflow --githubToken "${{ secrets.GITHUB_TOKEN }}"
      - name: ğŸ¥™ Aggregate by topics
        run: |
          .build/release/gallery-workflow aggregate
      - name: ğŸ§¹ Format
        run: |
          brew install yq
          ./.github/outputpretty.sh
      - name: â¬†ï¸ Push
        run: |
          rm -f .build/release/gallery-workflow
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -a -m "ğŸ”„ Update"
          ./.github/push.sh "master" "${{ secrets.GITHUB_TOKEN }}"
